version: '3.9'

services:
  simplesurance-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_PORT=8090
      - PREVIOUS_TIME=60
      - FILE_LOCATION=../files_repository/file.txt
    ports:
      - 8090:8090
